name: Create Release
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Semantic Version Number (i.e., 5.5.0 or patch, minor, major, prepatch, preminor, premajor, prerelease)'
        required: true
        default: patch
jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: main
          ssh-key: ${{ secrets.CMU_DELPHI_DEPLOY_MACHINE_SSH }}
      - name: Reset main branch
        run: |
          git fetch origin dev:dev
          git reset --hard origin/dev
#      - name: Change version number
#        id: version
#        run: |
#          echo -n "::set-output name=next_tag::"
#          npm version --no-git-tag-version ${{ github.event.inputs.versionName }}
#      - name: Create pull request into main
#        uses: peter-evans/create-pull-request@v3
#        with:
#          branch: release/${{ steps.version.outputs.next_tag }}
#          commit-message: 'chore: release ${{ steps.version.outputs.next_tag }}'
#          base: main
#          title: Release ${{ steps.version.outputs.next_tag }}
#          labels: chore
#          reviewers: krivard
#          # assignees:
#          body: |
#            Releasing ${{ steps.version.outputs.next_tag }}.
      - name: Check out epidata & copy files
        run:
          cd ..
          git clone https://github.com/cmu-delphi/delphi-epidata
          cp www-covidcast/src/stores/descriptions.raw.txt delphi-epidata/src/server/endpoints/covidcast_utils/descriptions.raw.txt
          cp www-covidcast/src/stores/questions.raw.txt delphi-epidata/src/server/endpoints/covidcast_utils/questions.raw.txt
      - name: Create PR to epidata
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "www-covidcast-sync"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_repository: "cmu-delphi/delphi-epidata"
